# Generated by Django 3.2 on 2021-11-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211127_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_json',
            new_name='itemsjson',
        ),
    ]
