# Generated by Django 3.2 on 2021-11-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_items_json_order_itemsjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='itemsjson',
        ),
    ]
